language : python
sudo: false
python:
    - "3.3"
    - "3.4"
    - "3.5"

before_install:
    - pip install pytest
    - pip install coveralls

script:
    - python3 -m coverage run --source seamus -m py.test

after_success:
    - coveralls